version: "3.1"

services:

  flightassist:
    image: flightassist:latest
    environment:
      - DEVMODE=true
      - DEV_URL=http://localhost:3000/
      - DEPLOY=compose
      - FORCE_FLIGHT_VIEW=true
      - USE_WEATHER_SERVICE=true
      - FLIGHTSTATS_APP_ID=<insert app ID>
      - FLIGHTSTATS_APP_KEY=<insert app key>
      - TRIPIT_API_KEY=<insert API key>
      - TRIPIT_API_SECRET=<insert API secret>
      - CLOUDANT_URL=<insert cloudant URL from Bluemix credentials view>
    ports:
      - "3000:3000"
    networks:
      - fassist-front
      - fassist-back
    depends_on:
      - weather-service

  weather-service:
    image: weather-service:latest
    networks:
      - fassist-back
    ports:
      - "5000:5000"
    environment:
      - WEATHER_URL=<insert Weather company URL from Bluemix credentials view>
      - DEPLOY=compose

networks:
  fassist-back:
  fassist-front:
