---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      bash -n *.sh
- name: DEPLOY
  inputs: 
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
       #!/bin/bash
       cf create-service cloudantNoSQLDB Lite mycloudant
       cf create-service weatherinsights Free-v2 myweatherinsights
       cf push "${CF_APP}"
       # View logs
       # cf logs "${CF_APP}" --recent
- name: DEPLOY
  inputs: 
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: BLUEMIX_USER
    type: text
  - name: BLUEMIX_PASSWORD
    type: secure
  - name: BLUEMIX_ACCOUNT
    type: secure
  - name: CLUSTER_NAME
    type: text
  - name: API_KEY
    type: secure
    
  - name: flightstats-app-id
    type: secure
  - name: flightstats-app-key
    type: secure
  - name: tripit-api-key
    type: secure
  - name: tripit-api-secret
    type: secure
  - name: openwhisk-auth
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      ./scripts/install_bx.sh
      ./scripts/bx_login.sh
      ./scripts/deploy.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api-integration.stage1.ng.bluemix.net/v1/messaging/webhook/publish
